[server]
headless = true
maxUploadSize = 500
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#F4B400"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#17202A"

